export const CREATE_NEW_GRADUATION_REQUEST = 'CREATE_NEW_GRADUATION_REQUEST';
export const CREATE_NEW_GRADUATION_SUCCESS = 'CREATE_NEW_GRADUATION_SUCCESS';
export const CREATE_NEW_GRADUATION_ERROR = 'CREATE_NEW_GRADUATION_ERROR';