export const CREATE_NEW_COMPANY_REQUEST = 'CREATE_NEW_COMPANY_REQUEST';
export const CREATE_NEW_COMPANY_SUCCESS = 'CREATE_NEW_COMPANY_SUCCESS';
export const CREATE_NEW_COMPANY_ERROR = 'CREATE_NEW_COMPANY_ERROR';