export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const RESET_UPDATE_PROFILE = 'RESET_UPDATE_PROFILE';


export const CREATE_GRADUATION = 'CREATE_GRADUATION';
export const RESET_CREATE_GRADUATION = 'RESET_CREATE_GRADUATION';

export const EDIT_GRADUATION = 'EDIT_GRADUATION';
export const RESET_EDIT_GRADUATION = 'RESET_EDIT_GRADUATION';

export const DELETE_GRADUATION = 'DELETE_GRADUATION';
export const RESET_DELETE_GRADUATION = 'RESET_DELETE_GRADUATION';



export const CREATE_WORK = 'CREATE_WORK';
export const RESET_CREATE_WORK = 'RESET_CREATE_WORK';

export const EDIT_WORK = 'EDIT_WORK';
export const RESET_EDIT_WORK = 'RESET_EDIT_WORK';

export const DELETE_WORK = 'DELETE_WORK';
export const RESET_DELETE_WORK = 'RESET_DELETE_WORK';


export const CREATE_COMPANY = 'CREATE_COMPANY';
export const RESET_CREATE_COMPANY = 'RESET_CREATE_COMPANY';